/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	netpolv1 "github.com/nokia/danm-utils/crd/api/netpol/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDanmNetworkPolicies implements DanmNetworkPolicyInterface
type FakeDanmNetworkPolicies struct {
	Fake *FakeNetpolV1
	ns   string
}

var danmnetworkpoliciesResource = schema.GroupVersionResource{Group: "netpol", Version: "v1", Resource: "danmnetworkpolicies"}

var danmnetworkpoliciesKind = schema.GroupVersionKind{Group: "netpol", Version: "v1", Kind: "DanmNetworkPolicy"}

// Get takes name of the danmNetworkPolicy, and returns the corresponding danmNetworkPolicy object, and an error if there is any.
func (c *FakeDanmNetworkPolicies) Get(name string, options v1.GetOptions) (result *netpolv1.DanmNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(danmnetworkpoliciesResource, c.ns, name), &netpolv1.DanmNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netpolv1.DanmNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of DanmNetworkPolicies that match those selectors.
func (c *FakeDanmNetworkPolicies) List(opts v1.ListOptions) (result *netpolv1.DanmNetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(danmnetworkpoliciesResource, danmnetworkpoliciesKind, c.ns, opts), &netpolv1.DanmNetworkPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &netpolv1.DanmNetworkPolicyList{ListMeta: obj.(*netpolv1.DanmNetworkPolicyList).ListMeta}
	for _, item := range obj.(*netpolv1.DanmNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested danmNetworkPolicies.
func (c *FakeDanmNetworkPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(danmnetworkpoliciesResource, c.ns, opts))

}

// Create takes the representation of a danmNetworkPolicy and creates it.  Returns the server's representation of the danmNetworkPolicy, and an error, if there is any.
func (c *FakeDanmNetworkPolicies) Create(danmNetworkPolicy *netpolv1.DanmNetworkPolicy) (result *netpolv1.DanmNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(danmnetworkpoliciesResource, c.ns, danmNetworkPolicy), &netpolv1.DanmNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netpolv1.DanmNetworkPolicy), err
}

// Update takes the representation of a danmNetworkPolicy and updates it. Returns the server's representation of the danmNetworkPolicy, and an error, if there is any.
func (c *FakeDanmNetworkPolicies) Update(danmNetworkPolicy *netpolv1.DanmNetworkPolicy) (result *netpolv1.DanmNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(danmnetworkpoliciesResource, c.ns, danmNetworkPolicy), &netpolv1.DanmNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netpolv1.DanmNetworkPolicy), err
}

// Delete takes name of the danmNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeDanmNetworkPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(danmnetworkpoliciesResource, c.ns, name), &netpolv1.DanmNetworkPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDanmNetworkPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(danmnetworkpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &netpolv1.DanmNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched danmNetworkPolicy.
func (c *FakeDanmNetworkPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *netpolv1.DanmNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(danmnetworkpoliciesResource, c.ns, name, pt, data, subresources...), &netpolv1.DanmNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netpolv1.DanmNetworkPolicy), err
}
