/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/nokia/danm-utils/crd/api/netpol/v1"
	scheme "github.com/nokia/danm-utils/crd/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DanmNetworkPoliciesGetter has a method to return a DanmNetworkPolicyInterface.
// A group's client should implement this interface.
type DanmNetworkPoliciesGetter interface {
	DanmNetworkPolicies(namespace string) DanmNetworkPolicyInterface
}

// DanmNetworkPolicyInterface has methods to work with DanmNetworkPolicy resources.
type DanmNetworkPolicyInterface interface {
	Create(*v1.DanmNetworkPolicy) (*v1.DanmNetworkPolicy, error)
	Update(*v1.DanmNetworkPolicy) (*v1.DanmNetworkPolicy, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.DanmNetworkPolicy, error)
	List(opts metav1.ListOptions) (*v1.DanmNetworkPolicyList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DanmNetworkPolicy, err error)
	DanmNetworkPolicyExpansion
}

// danmNetworkPolicies implements DanmNetworkPolicyInterface
type danmNetworkPolicies struct {
	client rest.Interface
	ns     string
}

// newDanmNetworkPolicies returns a DanmNetworkPolicies
func newDanmNetworkPolicies(c *NetpolV1Client, namespace string) *danmNetworkPolicies {
	return &danmNetworkPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the danmNetworkPolicy, and returns the corresponding danmNetworkPolicy object, and an error if there is any.
func (c *danmNetworkPolicies) Get(name string, options metav1.GetOptions) (result *v1.DanmNetworkPolicy, err error) {
	result = &v1.DanmNetworkPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("danmnetworkpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DanmNetworkPolicies that match those selectors.
func (c *danmNetworkPolicies) List(opts metav1.ListOptions) (result *v1.DanmNetworkPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DanmNetworkPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("danmnetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested danmNetworkPolicies.
func (c *danmNetworkPolicies) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("danmnetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a danmNetworkPolicy and creates it.  Returns the server's representation of the danmNetworkPolicy, and an error, if there is any.
func (c *danmNetworkPolicies) Create(danmNetworkPolicy *v1.DanmNetworkPolicy) (result *v1.DanmNetworkPolicy, err error) {
	result = &v1.DanmNetworkPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("danmnetworkpolicies").
		Body(danmNetworkPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a danmNetworkPolicy and updates it. Returns the server's representation of the danmNetworkPolicy, and an error, if there is any.
func (c *danmNetworkPolicies) Update(danmNetworkPolicy *v1.DanmNetworkPolicy) (result *v1.DanmNetworkPolicy, err error) {
	result = &v1.DanmNetworkPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("danmnetworkpolicies").
		Name(danmNetworkPolicy.Name).
		Body(danmNetworkPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the danmNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *danmNetworkPolicies) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("danmnetworkpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *danmNetworkPolicies) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("danmnetworkpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched danmNetworkPolicy.
func (c *danmNetworkPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DanmNetworkPolicy, err error) {
	result = &v1.DanmNetworkPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("danmnetworkpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
